### ISSUE TITLE
Многопоточное программирование п. 4.8

### ISSUE THREAD

**Issue by ghost** [loginov-dmitry/multithread#1]
Добрый день, Дмитрий!
Отличный материал, спасибо за работу!

в особенностях Вы пишете:
> Внимание! Данный подход к организации цикла ожидания имеет недостатки. Например, если из дополнительного потока произойдет вызов функции Syncronize, либо SendMessage, то цикл ожидания никогда не дождётся окончания работы потока, возникнет взаимная блокировка.

Но почему не решить эту проблему вставкой в цикл ожидания "Application.ProcessMessages"?

**Comment by loginov-dmitry** [comment]
Добрый день! 
Я не люблю использовать Application.ProcessMessages.
Данный метод слишком часто приводит к проблемам. Это самый настоящий костыль, Старайтесь никогда его не использовать. Если требуется организовать ожидание в gui, рассмотрите использование модальной формы.
